ART_OF_HAPPINESS_CHAPTERS_PAGE_NUMBERS = [
    ["TRANSFORMING DISSATISFACTION AT WORK", 24],
    ["THE HUMAN FACTOR", 48],
    ["MAKING MONEY", 62],
    ["STRIKING A BALANCE: BOREDOM AND CHALLENGE", 80],
    ["JOB, CAREER, AND CALLING", 110],
    ["SELF-UNDERSTANDING", 130],
    ["WORK AND IDENTITY", 152],
    ["RIGHT LIVELIHOOD", 170],
    ["HAPPINESS AT WORK", 188],
    ["EPILOGUE", 218],
    ["APPENDIX", 222],
]


ETHICS_FOR_THE_MILENNIUM_PAGE_NUMBERS = [
    ["MODERN SOCIETY AND THE QUEST FOR HUMAN HAPPINESS", 9],
    ["NO MAGIC, NO MYSTERY", 14],
    ["DEPENDENT ORIGINATION AND THE NATURE OF REALITY", 20],
    ["REDEFINING THE GOAL", 25],
    ["THE SUPREME EMOTION", 30],
    ["THE ETHIC OF RESTRAINT", 37],
    ["THE ETHIC OF VIRTUE", 44],
    ["THE ETHIC OF COMPASSION", 52],
    ["ETHICS AND SUFFERING", 55],
    ["THE NEED FOR DISCERNMENT", 59],
    ["UNIVERSAL RESPONSIBILITY", 65],
    ["LEVELS OF COMMITMENT", 69],
    ["ETHICS IN SOCIETY", 71],
    ["PEACE AND DISARMAMENT", 79],
    ["THE ROLE OF RELIGION IN MODERN SOCIETY", 85],
    ["AN APPEAL", 90],
]