ART_OF_HAPPINESS_CHAPTERS_PAGE_NUMBERS = [
    ["TRANSFORMING DISSATISFACTION AT WORK", 24],
    ["THE HUMAN FACTOR", 48],
    ["MAKING MONEY", 62],
    ["STRIKING A BALANCE: BOREDOM AND CHALLENGE", 80],
    ["JOB, CAREER, AND CALLING", 110],
    ["SELF-UNDERSTANDING", 130],
    ["WORK AND IDENTITY", 152],
    ["RIGHT LIVELIHOOD", 170],
    ["HAPPINESS AT WORK", 188],
    ["EPILOGUE", 218],
    ["APPENDIX", 222],
]
