FREEDOM_IN_EXILE_PAGE_NUMBERS = [['HOLDER OF THE  WHITE LOTUS', 1, 18], 
                            ['THE LION THRONE', 16, 33], 
                            ['INVASION: THE STORM BREAKS', 49, 66], 
                            ['REFUGE IN THE SOUTH', 58, 75], 
                            ['IN COMMUNIST CHINA', 82, 99], 
                            ['ESCAPE INTO EXILE', 123, 140], 
                            ['A DESPERATE YEAR', 144, 161], 
                            ['A WOLF IN MONK’S ROBES', 176, 193], 
                            ['FROM EAST TO WEST', 194, 211], 
                            ['OF ‘MAGIC AND MYSTERY’', 209, 226], 
                            ['THE NEWS FROM TIBET', 221, 238], 
                            ['INITIATIVES FOR PEACE', 238, 255], 
                            ['UNIVERSAL  RESPONSIBILITY AND  THE GOOD HEART', 254, 271], 
                            ['INDEX', 273, 290]]